### ISSUE TITLE
Getting preserve from undefined

### ISSUE THREAD

**Issue by w4zZz4p** [mrcgrtz/postcss-opacity-percentage#15]
https://github.com/mrcgrtz/postcss-opacity-percentage/blob/f12f09d04f26dc0db7114c8f41c4bae330d44202/index.js#L11

This should be:
```
module.exports = ({preserve = false} = {}) => ({ 
```

**Comment by mrcgrtz** [comment]
Thank you! It is fixed in [v1.1.1](https://github.com/mrcgrtz/postcss-opacity-percentage/releases/tag/v1.1.1).
