### ISSUE TITLE
PostCSS Opacity Percentage engine support 

### ISSUE THREAD

**Issue by Antonio-Laguna** [mrcgrtz/postcss-opacity-percentage#17]
Hi there!

We've just integrated `postcss-opacity-percentage` into `postcss-preset-env`. We've started to get issues because the plugin right now indicates that it only works on Node >= 16 as per https://github.com/mrcgrtz/postcss-opacity-percentage/blob/main/package.json#L28-L30

Right now we're following what PostCSS is currently supporting which is every LTS version of Node. 

Which would look like:

```
"engines": {
   "node": "^12 || ^14 || >=16"
}
```

Are you open to fix this and/or get a PR to update this?

See https://github.com/csstools/postcss-plugins/issues/218 for more context

**Comment by Mitsunee** [comment]
I would like to add that there currently are no tests running for 12.x and 14.x

https://github.com/mrcgrtz/postcss-opacity-percentage/blob/0edbbf270e18ed651449112a924164ea31a86219/.github/workflows/test.yml#L9-L14

**Comment by artecoop** [comment]
This is critical, is breaking react deployments on Vercel for example.

**Comment by Antonio-Laguna** [comment]
@artecoop you can pin your postcss-preset-env dependency to 7.2.3. It's not critical for this package as the author didn't introduce this into the ecosystem, it was already like this and the onus is on us for having have failed at CI level which we're already fixing.

**Comment by artecoop** [comment]
`yarn why postcss-opacity-percentage` keep showing me `Found "postcss-opacity-percentage@1.1.1"`even after adding
```
 "resolutions": {
    "postcss-preset-env": "7.2.3"
},
```

or adding it to devdependencies directly

**Comment by Mitsunee** [comment]
> `yarn why postcss-opacity-percentage` keep showing me `Found "postcss-opacity-percentage@1.1.1"`even after adding
> 
> ```
>  "resolutions": {
>     "postcss-preset-env": "7.2.3"
> },
> ```
> 
> or adding it to devdependencies directly

@artecoop did you rerun `yarn` to update the lockfile after modifying your `package.json`? `yarn why` by itself only inspects the lockfile without making sure it is up-to-date

**Comment by mrcgrtz** [comment]
I added Node 12 and 14 as supported engines in [v1.1.2](https://www.npmjs.com/package/postcss-opacity-percentage/v/1.1.2).

Please let me know if there are still issues.

**Comment by Antonio-Laguna** [comment]
@mrcgrtz Thanks a lot for your swift response and apologies for bringing this here!

**Comment by artecoop** [comment]
Damn son! You guys did not give me the time to finish my lunch you fixed this. Thanks!
Yes, I nuked the node_modules and yarn.lock. Now its working and Vercel does not fail anymore
